<a href="https://colab.research.google.com/github/gonzagax00/Intelig-ncia-Artificial/blob/main/Python_DataScience_%5BVictorGabrielFigueiraGonzaga%5D%5BB%5D%5B6%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Exercícios de NumPy, SciPy, Pandas e Matplotlib**
________________________________________________________________________
Aluno: Victor Gabriel Figueira Gonzaga | RGM: 11241100198
Turma: 6B — Noturno


**1 - Exercícios de NumPy**

In [ ]:
# 1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

import numpy as np

array = np.random.randint(10, 101, 50)
print(array)

[80 40 95 17 36 49 11 79 72 98 23 71 42 68 67 53 38 79 66 77 60 26 24 36
 72 58 92 22 56 69 67 71 62 45 98 41 39 81 74 10 88 39 74 18 23 20 90 17
 89 81]


In [ ]:
# 2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

import numpy as np

matriz = np.arange(1,17).reshape(4,4)
print(matriz[-1])

[13 14 15 16]


In [ ]:
# 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª à 10ª posição por 1.

import numpy as np

array = np.zeros(15)
array[4:10] = 1
print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

import numpy as np

array = np.random.randint(1, 50, 100)

mediana = np.median(array)

valores, contagens = np.unique(array, return_counts=True)
moda = valores[np.argmax(contagens)]

print("Mediana:", mediana)
print("Moda:", moda)

Mediana: 21.0
Moda: 3


In [ ]:
# 5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3.

import numpy as np

array = np.random.randint(1, 101, 20)

array[array % 3 == 0] = -3

print(array)

[11 41 -3 28 -3 -3 89 17 92 -3 59 -3 52 11 68 52  4 -3 -3 35]


In [ ]:
# 6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma de cada coluna.

import numpy as np

matriz = np.random.rand(5, 5)

soma_colunas = np.sum(matriz, axis=0)

print("Matriz 5x5: \n", matriz)
print("Soma de cada coluna: \n", soma_colunas)


Matriz 5x5: 
 [[0.58919717 0.85999235 0.0642863  0.24156913 0.326742  ]
 [0.77257763 0.38454173 0.34714852 0.59471582 0.17735363]
 [0.33814493 0.32829478 0.36144319 0.5118746  0.17037608]
 [0.20132596 0.54401157 0.04392227 0.62038735 0.36614058]
 [0.66597225 0.82469387 0.34242085 0.00713688 0.2888408 ]]
Soma de cada coluna: 
 [2.56721794 2.9415343  1.15922112 1.97568377 1.32945309]


In [ ]:
# 7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

import numpy as np

array1 = np.random.rand(40)
array2 = np.random.rand(40)

correlacao = np.corrcoef(array1, array2)[0, 1]

print(correlacao)

0.11754436715755708


In [ ]:
# 8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus elementos ao quadrado.

import numpy as np

matriz = np.random.randint(1, 10, (3, 3))
print("Matriz original: \n", matriz)

matriz_quadrado = matriz ** 2
print("Matriz elevada ao quadrado: \n", matriz_quadrado)



Matriz original: 
 [[1 2 8]
 [6 4 2]
 [2 7 1]]
Matriz elevada ao quadrado: 
 [[ 1  4 64]
 [36 16  4]
 [ 4 49  1]]


In [ ]:
# 9. Crie um array com 10 números aleatórios e normalize seus valores entre 0 e 1.

import numpy as np

array = np.random.rand(10)
print("Array original: \n", array)

array_normalizado = (array - np.min(array)) / (np.max(array) - np.min(array))
print("Array normalizado: \n", array_normalizado)


Array original: 
 [0.72835144 0.24110425 0.45464005 0.50186692 0.38007786 0.19169803
 0.39020397 0.19225768 0.88301277 0.5822788 ]
Array normalizado: 
 [7.76279431e-01 7.14670342e-02 3.80350657e-01 4.48665225e-01
 2.72495017e-01 0.00000000e+00 2.87142643e-01 8.09544328e-04
 1.00000000e+00 5.64982552e-01]


In [ ]:
# 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

import numpy as np

matriz = np.eye(6)
print("Matriz identidade: \n", matriz)
matriz[np.diag_indices_from(matriz)]
print("Diagonal principal: \n", matriz)

Matriz identidade: 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Diagonal principal: 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
# 11. Gere um array de 100 números inteiros e encontre o valor que mais se repete no array.

import numpy as np

array = np.random.randint(1, 10, 100)
print("Array: \n", array)
valores, contagens = np.unique(array, return_counts=True)
valor_mais_repetido = valores[np.argmax(contagens)]
print("Valor mais repetido: \n", valor_mais_repetido)


Array: 
 [9 3 3 8 1 8 8 5 3 7 3 5 4 8 5 4 3 6 9 9 6 7 2 9 1 3 2 8 2 2 9 5 4 8 9 8 8
 3 5 5 8 1 3 3 4 4 2 5 2 2 6 8 3 3 9 9 7 5 7 7 2 4 4 5 4 4 6 4 9 2 8 1 2 5
 2 5 7 9 4 1 1 1 1 8 8 5 4 3 9 4 8 7 8 7 8 4 4 4 5 5]
Valor mais repetido: 
 4


In [ ]:
# 12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

import numpy as np

matriz = np.random.randint(1, 10, (4, 4))
print("Matriz: \n", matriz)
np.fill_diagonal(matriz, 7)
print("Matriz com diagonal principal 7: \n", matriz)


Matriz: 
 [[5 5 4 8]
 [1 9 4 9]
 [2 1 2 3]
 [1 3 7 3]]
Matriz com diagonal principal 7: 
 [[7 5 4 8]
 [1 7 4 9]
 [2 1 7 3]
 [1 3 7 7]]


In [ ]:
# 13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

import numpy as np

array = np.arange(2, 22, 2)
print("Array: \n", array)
soma_cumulativa = np.cumsum(array)
print("Soma cumulativa: \n", soma_cumulativa)



Array: 
 [ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: 
 [  2   6  12  20  30  42  56  72  90 110]


In [ ]:
# 14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.

import numpy as np

array = np.random.randint(1, 10, 10)
array2 = np.random.randint(1, 10, 10)
print("Array: \n", array)
print("Array2: \n", array2)
diferenca = np.abs(array - array2)
print("Diferença: \n", diferenca)

Array: 
 [3 2 3 5 6 8 1 6 2 8]
Array2: 
 [9 6 3 8 7 7 1 9 4 8]
Diferença: 
 [6 4 0 3 1 1 0 3 2 0]


In [ ]:
# 15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.

import numpy as np

array = np.random.randint(1, 100, 20)
print("Array: \n", array)
array[array > 50] = 50
print("Array com valores maiores que 50: \n", array)

Array: 
 [53 94 35 40 69 95 65 75 41 37 70 47 59 31 34 77 11 61 48 91]
Array com valores maiores que 50: 
 [50 50 35 40 50 50 50 50 41 37 50 47 50 31 34 50 11 50 48 50]


In [ ]:
# 16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.

import numpy as np

array = np.random.randint(1, 100, 12)
print("Array: \n", array)
matriz = array.reshape(3, 4)
print("Matriz: \n", matriz)

Array: 
 [21 82 75 98 47 53 63  2 46 99 84  5]
Matriz: 
 [[21 82 75 98]
 [47 53 63  2]
 [46 99 84  5]]


In [ ]:
# 17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.

import numpy as np

matriz = np.random.randint(1, 10, (4, 4))
print("Matriz: \n", matriz)
matriz_multiplicada = matriz * np.indices(matriz.shape)[0]
print("Matriz multiplicada: \n", matriz_multiplicada)

Matriz: 
 [[1 4 4 1]
 [1 5 5 3]
 [2 7 6 8]
 [3 4 5 7]]
Matriz multiplicada: 
 [[ 0  0  0  0]
 [ 1  5  5  3]
 [ 4 14 12 16]
 [ 9 12 15 21]]


In [ ]:
# 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.

import numpy as np

array = np.random.randint(1, 101, 10)
print("Array: \n", array)
array[array % 5 == 0] = 0
print("Array com valores múltiplos de 5: \n", array)


Array: 
 [78 99 66 89 85 98 93 11 98 41]
Array com valores múltiplos de 5: 
 [78 99 66 89  0 98 93 11 98 41]


In [ ]:
# 19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ãngulo entre eles (produto escalar normalizado).

import numpy as np

array = np.random.randint(1, 10, 20)
array2 = np.random.randint(1, 10, 20)
print("Array: \n", array)
print("Array2: \n", array2)
produto_escalar = np.dot(array, array2)
print("Produto escalar: \n", produto_escalar)

Array: 
 [9 6 8 8 4 5 1 1 3 8 7 7 2 9 1 9 8 9 2 7]
Array2: 
 [5 8 1 2 4 3 1 2 7 2 5 8 1 3 4 2 4 9 7 9]
Produto escalar: 
 520


In [ ]:
# 20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.

import numpy as np

matriz = np.random.randint(1, 10, (4, 4))
print("Matriz: \n", matriz)
valor_minimo = np.min(matriz, axis=1)
print("Valor mínimo de cada linha: \n", valor_minimo)


Matriz: 
 [[5 2 4 2]
 [7 3 6 2]
 [4 5 8 7]
 [7 1 4 6]]
Valor mínimo de cada linha: 
 [2 2 4 1]


**2 - Exercícios de SciPy**

In [ ]:
# 1. Calcule a integral da função f(x) = x 2 sin(x) no intervalo de 0 a π.

import numpy as np
from scipy import integrate

def f(x):
    return x**2 * np.sin(x)

resultado, erro = integrate.quad(f, 0, np.pi)
print("Resultado da integral:", resultado)
print('Erro estimado: ', erro)



Resultado da integral: 5.869604401089359
Erro estimado:  6.516569951530559e-14


In [ ]:
# 2. Resolva a equação diferencial dy dx = x − y, com y(0) = 1, no intervalo de 0 a 10.

from scipy.integrate import solve_ivp
import numpy as np

def eq_diferencial(x, y):
    return x - y

solucao = solve_ivp(eq_diferencial, [0, 10], [1], t_eval=np.linspace(0, 10, 100))
print(f'Tempos: {solucao.t}')
print(f'Solução y: {solucao.y[0]}')

Tempos: [ 0.          0.1010101   0.2020202   0.3030303   0.4040404   0.50505051
  0.60606061  0.70707071  0.80808081  0.90909091  1.01010101  1.11111111
  1.21212121  1.31313131  1.41414141  1.51515152  1.61616162  1.71717172
  1.81818182  1.91919192  2.02020202  2.12121212  2.22222222  2.32323232
  2.42424242  2.52525253  2.62626263  2.72727273  2.82828283  2.92929293
  3.03030303  3.13131313  3.23232323  3.33333333  3.43434343  3.53535354
  3.63636364  3.73737374  3.83838384  3.93939394  4.04040404  4.14141414
  4.24242424  4.34343434  4.44444444  4.54545455  4.64646465  4.74747475
  4.84848485  4.94949495  5.05050505  5.15151515  5.25252525  5.35353535
  5.45454545  5.55555556  5.65656566  5.75757576  5.85858586  5.95959596
  6.06060606  6.16161616  6.26262626  6.36363636  6.46464646  6.56565657
  6.66666667  6.76767677  6.86868687  6.96969697  7.07070707  7.17171717
  7.27272727  7.37373737  7.47474747  7.57575758  7.67676768  7.77777778
  7.87878788  7.97979798  8.08080808  8.181

In [8]:
# 3. Encontre as raízes da função f(x) = x 4 − 3x 3 + 2 utilizando SciPy.

from scipy.optimize import root

def f(x):
    return x**4 - 3*x**3 + 2

resultado = root(f, x0=-1)
print("Raiz:", resultado.x[0])

Raiz: 0.999999999999979


In [10]:
# 4. Use a função de otimização de SciPy para maximizar f(x) = −x 2+ 4x+ 1.

from scipy.optimize import minimize

def f(x):
    return -x**2 + 4*x + 1

resultado = minimize(lambda x: -f(x), x0=0)
print("x que maximiza f(x):", resultado.x[0])
print("Valor máximo de f(x):", f(resultado.x[0]))

x que maximiza f(x): 2.000000026187685
Valor máximo de f(x): 4.999999999999999


In [14]:
# 5. Calcule a transformada de Fourier de um sinal composto de sin(2πt) e cos(4πt).

from scipy.fft import fft
import numpy as np

t = np.linspace(0, 1, 500)
sinal = np.sin(2 * np.pi * t) + np.cos(4 * np.pi * t)

frequencias = fft(sinal)
print("Magnitude dos 5 primeiros componentes:", np.abs(frequencias[:5]))

Magnitude dos 5 primeiros componentes: [  1.         249.75164289 250.24455798   0.88914234   0.42863594]


In [35]:
# 6. Encontre a matriz inversa de uma matriz 5x5 de números aleatórios.

from scipy.linalg import inv
import numpy as np

matriz_5x5 = np.random.rand(5, 5)
inversa = inv(matriz_5x5)

print(f'Matriz:\n{matriz_5x5}')
print(f'Matriz Inversa:\n{inversa}')
print(f'Verificação (matriz × inversa):\n{np.dot(matriz_5x5, inversa)}')

Matriz:
[[0.1208843  0.12411765 0.60670049 0.13096568 0.35204503]
 [0.77103522 0.39564809 0.33698288 0.17106707 0.93565558]
 [0.93629588 0.54642606 0.78812481 0.31601249 0.26898524]
 [0.57786737 0.48893676 0.9294241  0.43168574 0.10998684]
 [0.83853365 0.86847921 0.89316505 0.35870872 0.2256448 ]]
Matriz Inversa:
[[-5.77898254e-01 -2.43139956e-01  2.92309708e+00 -9.40626039e-01
  -1.11623230e+00]
 [-3.42611819e-01  1.55810048e-01 -2.30881031e+00 -7.76448016e-01
   3.01919298e+00]
 [ 2.45187731e+00 -1.19830855e+00  1.49644331e+00 -1.39901440e+00
   4.15912890e-02]
 [-4.24843600e+00  2.42542638e+00 -4.21378485e+00  7.40247057e+00
  -2.01401195e+00]
 [ 5.14783913e-01  1.19138113e+00 -1.20105130e+00  2.53919209e-01
  -3.59956459e-03]]
Verificação (matriz × inversa):
[[ 1.00000000e+00 -4.96653684e-17  2.37829132e-16 -1.40816958e-17
  -1.68909408e-16]
 [-1.08109144e-16  1.00000000e+00  2.40534227e-16  1.59529169e-16
  -3.63401547e-16]
 [ 1.63358915e-16 -2.49707025e-16  1.00000000e+00  9.5668

In [20]:
# 7. Use a função de interpolação cúbica de SciPy para interpolar os dados (0, 0),(1, 2),(2, 3),(3, 5),(4, 4).

from scipy.interpolate import interp1d
import numpy as np

x = np.array([0, 1, 2, 3, 4])
y = np.array([0, 2, 3, 5, 4])

f_cubica = interp1d(x, y, kind='cubic')
x_novos = np.array([0.5, 1.5, 2.5, 3.5])
y_interpolados = f_cubica(x_novos)
print("Interpolados: ", y_interpolados)

Interpolados:  [1.34375 2.40625 4.03125 5.21875]


In [22]:
# 8. Resolva o sistema de equações 3x + 2y = 5 e x + 4y = 6.

from scipy import linalg
import numpy as np

A = np.array([[3, 2], [1, 4]])
B = np.array([5, 6])

solucao = linalg.solve(A, B)
print("Solução [x, y]:", solucao)

Solução [x, y]: [0.8 1.3]


In [23]:
# 9. Ajuste uma curva quadrática aos pontos (1, 2),(2, 4),(3, 5),(4, 7),(5, 8).

from scipy.optimize import curve_fit
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 7, 8])

def parabola(x, a, b, c):
    return a*x**2 + b*x + c

parametros, _ = curve_fit(parabola, x, y)
print("Parâmetros [a, b, c]:", parametros)


Parâmetros [a, b, c]: [-0.07142857  1.92857143  0.2       ]


In [24]:
# 10. Calcule a integral dupla da função f(x, y) = xy + x 2 no intervalo [0, 2] para x e [0, 1] para y.

from scipy import integrate

def f(y, x):
    return x*y + x**2

resultado, erro = integrate.dblquad(f, 0, 2, 0, 1)
print("Resultado:", resultado)

Resultado: 3.666666666666667


In [26]:
# 11. Encontre os autovalores e autovetores de uma matriz 4x4 de números inteiros aleatórios.

from scipy.linalg import eig
import numpy as np

A = np.random.randint(1, 10, size=(4, 4))
autovalores, autovetores = eig(A)

print(f'Autovalores:\n{autovalores}')
print(f'Autovetores:\n{autovetores}')

Autovalores:
[26.02353247+0.j  3.2622926 +0.j  0.36053463+0.j -2.6463597 +0.j]
Autovetores:
[[ 0.50663893  0.50948599 -0.56226463  0.30687349]
 [ 0.57516443 -0.58520623 -0.26725592 -0.38908937]
 [ 0.55534726 -0.49175703 -0.18772812  0.71115111]
 [ 0.32263337  0.39513633  0.75973081 -0.49870054]]


In [28]:
# 12. Resolva a equação e x − x 2 = 0 para encontrar a raiz mais próxima de x = 1.

from scipy.optimize import fsolve
import numpy as np

def equacao(x):
    return np.exp(x) - x**2

raiz = fsolve(equacao, 1)
print(f'Raiz: {raiz}')

Raiz: [-0.70346742]


In [30]:
#13. Calcule o determinante de uma matriz 6x6 de números aleatórios entre -10 e 10.

from scipy.linalg import det
import numpy as np

matriz_6x6 = np.random.uniform(-10, 10, size=(6, 6))
determinante = det(A)

print(f'Matriz:\n{matriz_6x6}')
print(f'Determinante: {determinante}')

Matriz:
[[ 4.72369285  8.21405352 -3.81284094  9.4186635  -2.15634931  0.06927113]
 [ 8.06248417  8.92947412  5.97672896 -6.58373959 -1.10929545  7.04043276]
 [ 5.3842981  -3.84742891  5.2225132   4.26718918 -1.97561706 -0.34161503]
 [-5.38748133 -1.58385756  7.56694089 -0.87022655 -2.06392323  2.5053722 ]
 [-1.57254753 -6.49997179  0.9842153   3.6503836   4.9406124  -3.54321648]
 [ 4.1961199   2.55206895 -2.79972913  2.67965401  5.71591149  5.18240464]]
Determinante: 500219.38830137165


In [38]:
# 14. Utilize a função de otimização multivariada para minimizar f(x, y) = (x−2)² + (y − 3)².

from scipy.optimize import minimize

def funcao(v):
    x, y = v
    return (x - 2)**2 + (y - 3)**2

resultado = minimize(funcao, [0, 0])
print(f'Mínimo em [x, y] = {resultado.x}')

Mínimo em [x, y] = [1.99999999 2.99999999]


In [40]:
# 15. Calcule a transformada de Fourier inversa de um sinal complexo gerado aleatoriamente.

from scipy.fft import ifft
import numpy as np

sinal_complexo = np.random.rand(10) + 1j * np.random.rand(10)
resultado = ifft(sinal_complexo)

print(np.allclose(fft(resultado), sinal_complexo))
print(f'Sinal complexo (5 primeiros):\n{sinal_complexo[:5]}')
print(f'Após ifft (5 primeiros):\n{resultado[:5]}')

True
Sinal complexo (5 primeiros):
[0.25284623+0.92815528j 0.45664475+0.761805j   0.60332488+0.80534543j
 0.67660717+0.8875589j  0.49986246+0.11007252j]
Após ifft (5 primeiros):
[ 0.48768684+0.63390692j -0.00531773+0.19523192j -0.03777608-0.12249075j
  0.04555814-0.0277059j  -0.12483968-0.04187273j]


In [42]:
# 16. Resolva a equação diferencial de segunda ordem d 2y dx2 +y = 0, com condições iniciais y(0) = 1 e y′ (0) = 0.

from scipy.integrate import solve_ivp
import numpy as np

def sistema(x, estado):
    y1, y2 = estado
    return [y2, -y1]

solucao = solve_ivp(sistema, [0, 10], [1, 0], t_eval=np.linspace(0, 10, 20))
print(f'Solução bate com cos(x): {np.allclose(solucao.y[0], np.cos(solucao.t))}')
print(f'Solução y (10 primeiros): {solucao.y[0][:10]}')

Solução bate com cos(x): False
Solução y (10 primeiros): [ 1.          0.86468278  0.49529806 -0.00833408 -0.50985535 -0.87298984
 -1.00023688 -0.8558565  -0.48034573  0.02563608]


In [44]:
# 17. Encontre a raiz cúbica de 27 utilizando SciPy.

from scipy.optimize import brentq

def f(x):
    return x**3 - 27

raiz = brentq(f, 0, 10)
print("Raiz cúbica: ", raiz)

Raiz cúbica:  3.0


In [46]:
# 18. Interpole os valores de uma função f(x) = x 2 nos pontos [1, 2, 3, 4, 5] utilizando spline cúbica.

from scipy.interpolate import CubicSpline
import numpy as np

x = np.array([1, 2, 3, 4, 5])
y = x**2
spline = CubicSpline(x, y)

y_interpolados = spline([1.5, 2.5, 3.5, 4.5])

print("Pontos originais (x):", x)
print("Pontos originais (y):", y)
print("Novos pontos (x):", x_novos)
print("Valores interpolados (y):", y_interpolados)

Pontos originais (x): [1 2 3 4 5]
Pontos originais (y): [ 1  4  9 16 25]
Novos pontos (x): [0.5 1.5 2.5 3.5]
Valores interpolados (y): [ 2.25  6.25 12.25 20.25]


In [47]:
# 19. Realize a transformada de Fourier de um sinal discreto composto de senos e cossenos.

from scipy.fft import fft
import numpy as np

t = np.linspace(0, 1, 50, endpoint=False)
sinal = np.sin(2*np.pi*5*t) + 0.5*np.cos(2*np.pi*10*t)
frequencias = fft(sinal)

print(f'Magnitudes (10 primeiras): {np.abs(frequencias[:10])}')

Magnitudes (10 primeiras): [7.99360578e-15 4.80164459e-15 1.45796945e-15 4.22007699e-15
 2.13776023e-15 2.50000000e+01 5.03287892e-15 6.88274499e-15
 6.47844146e-15 3.43371212e-15]


In [59]:
# 20. Resolva um sistema de equações lineares com três variáveis utilizando SciPy.

from scipy import linalg
import numpy as np

#   x +  y +  z = 6
#  2x +  y -  z = 1
#   x -  y + 2z = 5

A = np.array([[1, 1, 1],
              [2, 1, -1],
              [1, -1, 2]])
B = np.array([6, 1, 5])

solucao = linalg.solve(A, B)
x, y, z = solucao

print(f"[{x:.1f}, {y:.1f}, {z:.1f}]")

[1.0, 2.0, 3.0]


**3 - Exercícios de Pandas**