<a href="https://colab.research.google.com/github/gonzagax00/Intelig-ncia-Artificial/blob/main/Python_DataScience_%5BVictorGabrielFigueiraGonzaga%5D%5BB%5D%5B6%5D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1-Exercícios de NumPy**

In [ ]:
# 1. Crie um array unidimensional de 50 elementos contendo números inteiros aleatórios entre 10 e 100.

import numpy as np

array = np.random.randint(10, 101, 50)
print(array)

[80 40 95 17 36 49 11 79 72 98 23 71 42 68 67 53 38 79 66 77 60 26 24 36
 72 58 92 22 56 69 67 71 62 45 98 41 39 81 74 10 88 39 74 18 23 20 90 17
 89 81]


In [ ]:
# 2. Gere uma matriz 4x4 com números inteiros de 1 a 16 e extraia a última linha.

import numpy as np

matriz = np.arange(1,17).reshape(4,4)
print(matriz[-1])

[13 14 15 16]


In [ ]:
# 3. Crie um array de zeros com comprimento 15 e substitua os valores da 5ª à 10ª posição por 1.

import numpy as np

array = np.zeros(15)
array[4:10] = 1
print(array)

[0. 0. 0. 0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 4. Gere um array de 100 números inteiros aleatórios e encontre a mediana e a moda dos valores.

import numpy as np

array = np.random.randint(1, 50, 100)

mediana = np.median(array)

valores, contagens = np.unique(array, return_counts=True)
moda = valores[np.argmax(contagens)]

print("Mediana:", mediana)
print("Moda:", moda)

Mediana: 21.0
Moda: 3


In [ ]:
# 5. Crie um array de 20 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 3 por -3.

import numpy as np

array = np.random.randint(1, 101, 20)

array[array % 3 == 0] = -3

print(array)

[11 41 -3 28 -3 -3 89 17 92 -3 59 -3 52 11 68 52  4 -3 -3 35]


In [ ]:
# 6. Gere uma matriz 5x5 de números aleatórios entre 0 e 1 e encontre a soma de cada coluna.

import numpy as np

matriz = np.random.rand(5, 5)

soma_colunas = np.sum(matriz, axis=0)

print("Matriz 5x5: \n", matriz)
print("Soma de cada coluna: \n", soma_colunas)


Matriz 5x5: 
 [[0.58919717 0.85999235 0.0642863  0.24156913 0.326742  ]
 [0.77257763 0.38454173 0.34714852 0.59471582 0.17735363]
 [0.33814493 0.32829478 0.36144319 0.5118746  0.17037608]
 [0.20132596 0.54401157 0.04392227 0.62038735 0.36614058]
 [0.66597225 0.82469387 0.34242085 0.00713688 0.2888408 ]]
Soma de cada coluna: 
 [2.56721794 2.9415343  1.15922112 1.97568377 1.32945309]


In [ ]:
# 7. Crie dois arrays de números aleatórios e encontre a correlação entre eles.

import numpy as np

array1 = np.random.rand(40)
array2 = np.random.rand(40)

correlacao = np.corrcoef(array1, array2)[0, 1]

print(correlacao)

0.11754436715755708


In [ ]:
# 8. Gere uma matriz 3x3 com números inteiros aleatórios e eleve todos os seus elementos ao quadrado.

import numpy as np

matriz = np.random.randint(1, 10, (3, 3))
print("Matriz original: \n", matriz)

matriz_quadrado = matriz ** 2
print("Matriz elevada ao quadrado: \n", matriz_quadrado)



Matriz original: 
 [[1 2 8]
 [6 4 2]
 [2 7 1]]
Matriz elevada ao quadrado: 
 [[ 1  4 64]
 [36 16  4]
 [ 4 49  1]]


In [ ]:
# 9. Crie um array com 10 números aleatórios e normalize seus valores entre 0 e 1.

import numpy as np

array = np.random.rand(10)
print("Array original: \n", array)

array_normalizado = (array - np.min(array)) / (np.max(array) - np.min(array))
print("Array normalizado: \n", array_normalizado)


Array original: 
 [0.72835144 0.24110425 0.45464005 0.50186692 0.38007786 0.19169803
 0.39020397 0.19225768 0.88301277 0.5822788 ]
Array normalizado: 
 [7.76279431e-01 7.14670342e-02 3.80350657e-01 4.48665225e-01
 2.72495017e-01 0.00000000e+00 2.87142643e-01 8.09544328e-04
 1.00000000e+00 5.64982552e-01]


In [ ]:
# 10. Crie uma matriz identidade 6x6 e substitua a diagonal principal por valores crescentes de 1 a 6.

import numpy as np

matriz = np.eye(6)
print("Matriz identidade: \n", matriz)
matriz[np.diag_indices_from(matriz)]
print("Diagonal principal: \n", matriz)

Matriz identidade: 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]
Diagonal principal: 
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [1]:
# 11. Gere um array de 100 números inteiros e encontre o valor que mais se repete no array.

import numpy as np

array = np.random.randint(1, 10, 100)
print("Array: \n", array)
valores, contagens = np.unique(array, return_counts=True)
valor_mais_repetido = valores[np.argmax(contagens)]
print("Valor mais repetido: \n", valor_mais_repetido)


Array: 
 [9 3 3 8 1 8 8 5 3 7 3 5 4 8 5 4 3 6 9 9 6 7 2 9 1 3 2 8 2 2 9 5 4 8 9 8 8
 3 5 5 8 1 3 3 4 4 2 5 2 2 6 8 3 3 9 9 7 5 7 7 2 4 4 5 4 4 6 4 9 2 8 1 2 5
 2 5 7 9 4 1 1 1 1 8 8 5 4 3 9 4 8 7 8 7 8 4 4 4 5 5]
Valor mais repetido: 
 4


In [2]:
# 12. Crie uma matriz 4x4 e substitua os valores da diagonal principal por 7.

import numpy as np

matriz = np.random.randint(1, 10, (4, 4))
print("Matriz: \n", matriz)
np.fill_diagonal(matriz, 7)
print("Matriz com diagonal principal 7: \n", matriz)


Matriz: 
 [[5 5 4 8]
 [1 9 4 9]
 [2 1 2 3]
 [1 3 7 3]]
Matriz com diagonal principal 7: 
 [[7 5 4 8]
 [1 7 4 9]
 [2 1 7 3]
 [1 3 7 7]]


In [3]:
# 13. Crie um array contendo os 10 primeiros números pares e calcule sua soma cumulativa.

import numpy as np

array = np.arange(2, 22, 2)
print("Array: \n", array)
soma_cumulativa = np.cumsum(array)
print("Soma cumulativa: \n", soma_cumulativa)



Array: 
 [ 2  4  6  8 10 12 14 16 18 20]
Soma cumulativa: 
 [  2   6  12  20  30  42  56  72  90 110]


In [4]:
# 14. Calcule a diferença entre dois arrays de números aleatórios de mesmo comprimento e encontre a média das diferenças.

import numpy as np

array = np.random.randint(1, 10, 10)
array2 = np.random.randint(1, 10, 10)
print("Array: \n", array)
print("Array2: \n", array2)
diferenca = np.abs(array - array2)
print("Diferença: \n", diferenca)

Array: 
 [3 2 3 5 6 8 1 6 2 8]
Array2: 
 [9 6 3 8 7 7 1 9 4 8]
Diferença: 
 [6 4 0 3 1 1 0 3 2 0]


In [5]:
# 15. Gere um array contendo 20 números e substitua todos os valores maiores que 50 por 50.

import numpy as np

array = np.random.randint(1, 100, 20)
print("Array: \n", array)
array[array > 50] = 50
print("Array com valores maiores que 50: \n", array)

Array: 
 [53 94 35 40 69 95 65 75 41 37 70 47 59 31 34 77 11 61 48 91]
Array com valores maiores que 50: 
 [50 50 35 40 50 50 50 50 41 37 50 47 50 31 34 50 11 50 48 50]


In [6]:
# 16. Crie um array unidimensional e reorganize seus valores em uma matriz 3x4.

import numpy as np

array = np.random.randint(1, 100, 12)
print("Array: \n", array)
matriz = array.reshape(3, 4)
print("Matriz: \n", matriz)

Array: 
 [21 82 75 98 47 53 63  2 46 99 84  5]
Matriz: 
 [[21 82 75 98]
 [47 53 63  2]
 [46 99 84  5]]


In [7]:
# 17. Gere uma matriz 4x4 de números inteiros aleatórios e multiplique cada valor por sua posição na matriz.

import numpy as np

matriz = np.random.randint(1, 10, (4, 4))
print("Matriz: \n", matriz)
matriz_multiplicada = matriz * np.indices(matriz.shape)[0]
print("Matriz multiplicada: \n", matriz_multiplicada)

Matriz: 
 [[1 4 4 1]
 [1 5 5 3]
 [2 7 6 8]
 [3 4 5 7]]
Matriz multiplicada: 
 [[ 0  0  0  0]
 [ 1  5  5  3]
 [ 4 14 12 16]
 [ 9 12 15 21]]


In [11]:
# 18. Crie um array de 10 elementos contendo números entre 1 e 100 e substitua todos os valores múltiplos de 5 por 0.

import numpy as np

array = np.random.randint(1, 101, 10)
print("Array: \n", array)
array[array % 5 == 0] = 0
print("Array com valores múltiplos de 5: \n", array)


Array: 
 [78 99 66 89 85 98 93 11 98 41]
Array com valores múltiplos de 5: 
 [78 99 66 89  0 98 93 11 98 41]


In [12]:
# 19. Crie dois arrays de números inteiros aleatórios de tamanho 20 e calcule o ãngulo entre eles (produto escalar normalizado).

import numpy as np

array = np.random.randint(1, 10, 20)
array2 = np.random.randint(1, 10, 20)
print("Array: \n", array)
print("Array2: \n", array2)
produto_escalar = np.dot(array, array2)
print("Produto escalar: \n", produto_escalar)

Array: 
 [9 6 8 8 4 5 1 1 3 8 7 7 2 9 1 9 8 9 2 7]
Array2: 
 [5 8 1 2 4 3 1 2 7 2 5 8 1 3 4 2 4 9 7 9]
Produto escalar: 
 520


In [13]:
# 20. Crie uma matriz de números inteiros e encontre o valor mínimo de cada linha.

import numpy as np

matriz = np.random.randint(1, 10, (4, 4))
print("Matriz: \n", matriz)
valor_minimo = np.min(matriz, axis=1)
print("Valor mínimo de cada linha: \n", valor_minimo)


Matriz: 
 [[5 2 4 2]
 [7 3 6 2]
 [4 5 8 7]
 [7 1 4 6]]
Valor mínimo de cada linha: 
 [2 2 4 1]


**2-Exercícios de SciPy**